

<?php $this->headTitle($this->title); ?>


<div class="row">
           
    <div class="span4 pull-left">
        <h4><?php echo $this->escapeHtml($this->title); ?></h4>
        <h5>
            <span class="icon-list"></span> 
            <?php 
                echo (1==($count = $this->paginator->getTotalItemCount())) ? $count.' account' : $count.' account`s'; 
            ?>            
        </h5>
    </div>
    

        <form class="form-search" class="span4 pull-left" action="" method="get">
                <input type="text" name="filter" class="input-large search-query typeahead" autocomplete="off" id="search" data-provide="typeahead" placeholder="Search payment" value="<?php echo $_GET['filter']!=="" ? $_GET['filter'] : ''; ?>" style="padding: 11px 19px;font-size: 17.5px;">
                <button type="submit" class="btn btn-large">Search</button>
                <button type="submit" class="btn btn-large" name="filter">Clear</button>
        </form>

        
    <div class="span4 pull-right">
        <div class="pagination pagination-right">
            <?php // add at the end of the file after the table
            echo $this->paginationControl(
                // the paginator admin
                $this->paginator,
                'Sliding',
                // the partial to use to render the control
                array('partial/paginator.phtml', 'Account'),
                // the route to link to when a user clicks a control link
                array(
                    'route' => 'accounts'
                )
            );
            ?>
        </div>
    </div>


    <div class="content span12">

        <table class="table table-striped table-hover table-bordered">
            <tr>
                <th>Name</th>
                <th>Payments</th>
            </tr>
            <?php foreach ($this->paginator as $account) : ?>
                <tr>
                         <td>
                         
                                <div class="btn-group pull-right">  
                                        <a href="<?php echo $this->url('accounts', array('action'=>'add'));?>" class="btn btn-mini"><i class="icon-plus"></i>                          
                                        <a href="<?php echo $this->url('accounts',array('action'=>'edit', 'id' => $account->id));?>" class="btn btn-mini"><i class="icon-pencil"></i></a>
                                        <!--a href="<?php echo $this->url('accounts',array('action'=>'delete', 'id' => $account->id));?>" class=""btn btn-mini"><i class="icon-trash"></i></a--> 
                                        <a href="<?php echo $this->url('accounts',array('action'=>'activity', 'id' => $account->id));?>" class="btn btn-mini">
                                                <i class="icon-list"></i>
                                        </a>
                                </div>
                                
                                <p>
                                        <?php echo $this->escapeHtml($account->name);?>

                                        <span style="color:<?php echo $amounts[$account->id]['total']<0 ? 'red' : 'green'; ?>;">
                                                &pound;<?php echo number_format($amounts[$account->id]['total'],2); ?>
                                        </span>
                                </p>
                                
                                
                                
                        </td>

                        <td>
                                <?php
                                if (count($payments = $account->getPayments())>0) {
                                    foreach($payments AS $payment) : ?>
                                        <p>
                                                <div class="btn-group pull-right">   

                                                        <a href="<?php echo $this->url('payments',array('action'=>'add', 'id' => $account->id));?>" class="btn btn-mini">
                                                            <i class="icon-plus"></i>
                                                        </a>                                        
                                                        <a href="<?php echo $this->url('payments',array('action'=>'edit', 'id' => $payment->id));?>" class="btn btn-mini">
                                                            <i class="icon-pencil"></i>
                                                        </a>
                                                        <!--a href="<?php echo $this->url('payments',array('action'=>'delete', 'id' => $payment->id));?>" class="btn btn-mini">
                                                            <i class="icon-trash"></i>
                                                        </a-->
                                                        <a href="<?php echo $this->url('payments',array('action'=>'activity', 'id' => $payment->id));?>" class="btn btn-mini">
                                                                <i class="icon-list"></i>
                                                        </a>
                                                </div>

                                                <p class="<?php echo !$payment->active ? 'muted' : ''; ?> desc">
                                                        <?php //echo $payment->amount; ?>
                                                        <?php echo $payment->description; ?>                                        
                                                        <span style="color:<?php echo $amounts[$account->id][$payment->id][0]['amount']<0 ? 'red' : 'green'; ?>;">
                                                                &pound;<?php echo number_format($amounts[$account->id][$payment->id][0]['amount'],2); ?>
                                                        </span>
                                                </p>
                                             

                                        </p>
                                    <?php     
                                    endforeach;     
                                } else { ?>
                                        <a href="<?php echo $this->url('payments',array('action'=>'add', 'id' => $account->id));?>" class="btn btn-mini">
                                   		<i class="icon-plus"></i>
                                        </a>   
                                <?php } ?>
                        </td>
                </tr>
            <?php endforeach; ?>
        </table>
        
    </div>
    
       <script type="text/javascript">

    $(document).ready(function(){

        var accounts = [
                <?php foreach ($this->paymentTitles AS $paymentTitle){
                        echo "'$paymentTitle',";
                }
                ?>
        
        ];
 
        $('#search').typeahead({source: accounts});

    });  

    </script>
    
</div>
