

<?php $this->headTitle($this->title); ?>


<div class="row">
           
    <div class="span8 pull-left">
        <h4><?php echo $this->escapeHtml($this->title); ?></h4>
        <h5>
            <span class="icon-list"></span> 
            <?php 
                echo (1==($count = $this->paginator->getTotalItemCount())) ? $count.' account' : $count.' account`s'; 
            ?>            
        </h5>
    </div>
    
    
    <div class="span4 pull-right">
        <div class="pagination pagination-right">
            <?php // add at the end of the file after the table
            echo $this->paginationControl(
                // the paginator admin
                $this->paginator,
                'sliding',
                // the partial to use to render the control
                array('partial/paginator.phtml', 'Account'),
                // the route to link to when a user clicks a control link
                array(
                    'route' => 'accounts'
                )
            );
            ?>
        </div>
    </div>


    <div class="content span12">

        <table class="table table-striped table-hover table-bordered">
            <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Created</th>
                <th>Payments</th>
                <th><a href="<?php echo $this->url('accounts', array('action'=>'add'));?>" class="btn btn-mini pull-right"><i class="icon-plus"></i></a></th>
            </tr>
            <?php foreach ($this->paginator as $account) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($account->name);?></td>
                    <td><?php echo $account->active ? '<span class="badge badge-success">Enabled</span>' : '<span class="badge badge-important">Disabled</span>'; ?></td> 
                    <td><?php echo $this->escapeHtml($account->created);?></td>
                    <td>
                        <?php
                        if ($payments = $account->getPayments()) {
                            foreach($payments AS $payment) : ?>
                                <p>
                                    <div class="btn-group pull-right">                                
                                        <a href="<?php echo $this->url('payments',array('action'=>'edit', 'id' => $payment->id));?>" class="btn btn-mini">
                                            <i class="icon-pencil"></i>
                                        </a>
                                        <a href="<?php echo $this->url('payments',array('action'=>'delete', 'id' => $payment->id));?>" class="btn btn-mini">
                                            <i class="icon-trash"></i>
                                        </a>
                                    </div>
                                    &pound;<?php echo $payment->amount; ?> <?php echo $payment->description; ?>
                                </p>
                            <?php     
                            endforeach;     
                        }
                        ?>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->url('payments',array('action'=>'add', 'id' => $account->id));?>" class="btn"><i class="icon-add"></i></a>
                            <a href="<?php echo $this->url('accounts',array('action'=>'edit', 'id' => $account->id));?>" class="btn"><i class="icon-pencil"></i></a>
                            <a href="<?php echo $this->url('accounts',array('action'=>'delete', 'id' => $account->id));?>" class="btn"><i class="icon-trash"></i></a> 
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
        
    </div>
    
    
</div>