

<?php $this->headTitle('Charts'); ?>

<div class="row">
    <ul class="nav nav-tabs nav-stacked span2">
        <li class="nav-header">Charts</li>
        <li class="active"><a href="">Summary</a></li>
        <li><a href="">Summary</a></li>
        <li><a href="">Summary</a></li>
        <li><a href="">Summary</a></li>
    </ul>

    <div class="span10" style="height:600px;">
        <canvas id="canvas" width="100" height="200"></canvas>
    </div>
</div>




        
<script>

var barChartData = {
    labels : [<?php echo '"'.implode('","',$this->labels).'"'; ?>],
    datasets : [
    {
    fillColor : "rgba(220,220,220,0.5)",
    strokeColor : "rgba(220,220,220,1)",
    data : [<?php echo implode(',',$this->data); ?>]
    },
    /*{
    fillColor : "rgba(151,187,205,0.5)",
    strokeColor : "rgba(151,187,205,1)",
    data : [28,48,40,19,96,27,100]
    }*/
    ]

}

function redraw(canvas){
    var myLine = new Chart(canvas.getContext("2d")).Bar(barChartData);   
    canvas.width  = canvas.parentNode.offsetWidth;
    canvas.height = canvas.parentNode.offsetHeight;
    
}


var canvas = document.getElementById("canvas");
window.addEventListener("resize", redraw(canvas));
redraw(canvas);
</script>
