

<?php $this->headTitle('Charts'); ?>

<canvas id="canvas" width="1200" height="500"></canvas>


        
<script>

var barChartData = {
    labels : [<?php echo '"'.implode('","',$this->labels).'"'; ?>],
    datasets : [
    {
    fillColor : "rgba(220,220,220,0.5)",
    strokeColor : "rgba(220,220,220,1)",
    data : [<?php echo implode(',',$this->data); ?>]
    },
    /*{
    fillColor : "rgba(151,187,205,0.5)",
    strokeColor : "rgba(151,187,205,1)",
    data : [28,48,40,19,96,27,100]
    }*/
    ]

}

var myLine = new Chart(document.getElementById("canvas").getContext("2d")).Bar(barChartData);
</script>