

<?php $this->headTitle($this->statement->getStatementTitle()); ?>



<canvas id="myChart" width="400" height="400"></canvas>

<script type="text/javascript">
    //Get context with jQuery - using jQuery's .get() method.
    var ctx = $("#myChart").get(0).getContext("2d");
    //This will get the first returned node in the jQuery collection.
    var myNewChart = new Chart(ctx);
    
    
    
    var data = {
	labels : ["January","February","March","April","May","June","July"],
	datasets : [
		{
			fillColor : "rgba(220,220,220,0.5)",
			strokeColor : "rgba(220,220,220,1)",
			pointColor : "rgba(220,220,220,1)",
			pointStrokeColor : "#fff",
			data : [65,59,90,81,56,55,40]
		},
		{
			fillColor : "rgba(151,187,205,0.5)",
			strokeColor : "rgba(151,187,205,1)",
			pointColor : "rgba(151,187,205,1)",
			pointStrokeColor : "#fff",
			data : [28,48,40,19,96,27,100]
		}
	]
}
    
    Line.defaults = {
				
	//Boolean - If we show the scale above the chart data			
	scaleOverlay : false,
	
	//Boolean - If we want to override with a hard coded scale
	scaleOverride : false,
	
	//** Required if scaleOverride is true **
	//Number - The number of steps in a hard coded scale
	scaleSteps : null,
	//Number - The value jump in the hard coded scale
	scaleStepWidth : null,
	//Number - The scale starting value
	scaleStartValue : null,

	//String - Colour of the scale line	
	scaleLineColor : "rgba(0,0,0,.1)",
	
	//Number - Pixel width of the scale line	
	scaleLineWidth : 1,

	//Boolean - Whether to show labels on the scale	
	scaleShowLabels : false,
	
	//Interpolated JS string - can access value
	scaleLabel : "<%=value%>",
	
	//String - Scale label font declaration for the scale label
	scaleFontFamily : "'Arial'",
	
	//Number - Scale label font size in pixels	
	scaleFontSize : 12,
	
	//String - Scale label font weight style	
	scaleFontStyle : "normal",
	
	//String - Scale label font colour	
	scaleFontColor : "#666",	
	
	///Boolean - Whether grid lines are shown across the chart
	scaleShowGridLines : true,
	
	//String - Colour of the grid lines
	scaleGridLineColor : "rgba(0,0,0,.05)",
	
	//Number - Width of the grid lines
	scaleGridLineWidth : 1,	
	
	//Boolean - Whether the line is curved between points
	bezierCurve : true,
	
	//Boolean - Whether to show a dot for each point
	pointDot : true,
	
	//Number - Radius of each point dot in pixels
	pointDotRadius : 3,
	
	//Number - Pixel width of point dot stroke
	pointDotStrokeWidth : 1,
	
	//Boolean - Whether to show a stroke for datasets
	datasetStroke : true,
	
	//Number - Pixel width of dataset stroke
	datasetStrokeWidth : 2,
	
	//Boolean - Whether to fill the dataset with a colour
	datasetFill : true,
	
	//Boolean - Whether to animate the chart
	animation : true,

	//Number - Number of animation steps
	animationSteps : 60,
	
	//String - Animation easing effect
	animationEasing : "easeOutQuart",

	//Function - Fires when the animation is complete
	onAnimationComplete : null
	
}

new Chart(ctx).Bar(data,options);
    
</script>



<?php return; ?>


<div class="row">
           
    <div class="span4 pull-left">
        <h4><?php echo $this->statement->getStatementTitle(); ?></h4>
        <h5>
            <span class="icon-list"></span> 
            <?php 
                //echo (1==($count = $this->paginator->getTotalItemCount())) ? $count.' date' : $count.' date`s'; 
                echo (1==($count = $this->statement->count())) ? $count.' Day' : $count.' Day`s'; 
            ?>    
            &pound;<?php echo number_format($this->statement->getBalance($this->statement->getEnd()->getDate()),2); ?>
        </h5>
    </div>
    
    
    <div class="span8 pull-right">
                
        <div class="pagination pull-right"> 
            <ul>
                <?php foreach($this->months AS $month): ?>

                    <li 
                        class="<?php echo $this->today->format('Y-m')==$month->format('Y-m') ? 'active' : ($month->format('Y-m')=='2013-06' ? 'disabled' : ''); ?>" 
                        >
                        <a href="<?php echo $month->format('Y-m')=='2013-06' ? '#' : $this->url('statement', array('datestamp'=>$month->format('Y-m-d')));?>" >
                            <?php echo $month->format('M Y'); ?>
                        </a>
                    </li>

                <?php endforeach; ?>
            </ul>
        </div>
        
        
    </div>


    <div class="content span12">

        <table class="table table-striped table-hover table-bordered">
            <tr>
                <th>Date</th>
                <th>Balance</th>
                <th>Transactions</th>
                <!--th><a href="<?php echo $this->url('dates', array('action'=>'add'));?>" class="btn btn-mini pull-right"><i class="icon-plus"></i></a></th-->
            </tr>
            <?php foreach ($this->statement as $date) : ?>
                <tr>
                    <td>
                        <?php //echo $this->escapeHtml($date->date); ?>                        
                        <?php echo $this->escapeHtml($date->getDate()->format('D jS \of M')); ?>
                    </td> 
                    <td>
                        &pound;<?php echo $this->statement->getBalance($date->getDate()); ?>                        
                    </td>
                    <td>     
                        Total: &pound;<?php echo $date->getTransactionTotal(); ?>
                        <a href="<?php echo $this->url('transactions',array('action'=>'add', 'id' => $date->getId()));?>" class="btn btn-mini pull-right">
                            <i class="icon-plus"></i>
                        </a>
                        <br />
                        <br />
                        <?php
                        if ($transactions = $date->getTransactions()) {
                            foreach($transactions AS $transaction) : ?>
                                <div class="btn-group pull-right">                                       
                                    <a href="<?php echo $this->url('transactions',array('action'=>'edit', 'id' => $transaction->id));?>" class="btn btn-mini">
                                        <i class="icon-pencil"></i>
                                    </a>
                                    <!--a href="<?php echo $this->url('transactions',array('action'=>'delete', 'id' => $transaction->id));?>" class="btn btn-mini">
                                        <i class="icon-trash"></i>
                                    </a-->
                                </div>                                
                                <p <?php echo $transaction->active ? "" : "class='muted'"; ?>>
                                    &pound;<?php echo $transaction->amount; ?> <?php echo $transaction->payment->description; ?> - <?php echo $transaction->payment->account->name; ?>&nbsp;
                                    <?php if ($transaction->comment!=='') : ?>
                                        <small><i><?php echo $transaction->comment; ?></i></small>
                                    <?php endif; ?>
                                </p>                         
                            <?php     
                            endforeach;     
                        }
                        ?>
                    </td>
                    <!--td>
                        <div class="btn-group pull-right">                            
                            <a href="<?php echo $this->url('dates',array('action'=>'edit', 'id' => $date->getId()));?>" class="btn"><i class="icon-pencil"></i></a>
                            <a href="<?php echo $this->url('dates',array('action'=>'delete', 'id' => $date->getId()));?>" class="btn"><i class="icon-trash"></i></a> 
                        </div>
                    </td-->
                </tr>
            <?php endforeach; ?>
        </table>
        
    </div>
    
    
</div>