

<?php $this->headTitle($this->statement->getStatementTitle()); ?>

<style>

.table tbody tr.checked td {
    opacity: 0.5;
    filter: alpha(opacity=50); /* For IE8 and earlier */
}

.table tbody tr.checked td div.transactions-listing, .table tbody tr.checked hr{
    display:none;
}

.table tbody tr.checked td p.amt, .table tbody tr.checked td p.amt-negative {
    font-size:12px;
}

.date {

}

p.amt {
    font-size: 20px;
    color:#00dd00;
}

.amt-negative {
    font-size: 20px;
    color:#dd0000;
}



</style>


<div class="row">
           
    <div class="span4 pull-left">
        <h4>
            <!--a href='<?php echo $this->url('statement',array('action'=>'activity', 'datestamp' => $this->today->format('Y-m')));?>' title='<?php echo $this->statement->getStatementTitle(); ?>'-->
                <?php echo $this->statement->getStatementTitle(); ?>
            <!--/a-->
        </h4>
        <h5>
                <a href="<?php echo $this->url('analysis',array('action'=>'month', 'datestamp' => $this->today->format('Y-m')));?>" class="btn btn-mini">
                        <i class="icon-picture"></i>
                </a>
            <?php 
                //echo (1==($count = $this->paginator->getTotalItemCount())) ? $count.' date' : $count.' date`s'; 
                echo (1==($count = $this->statement->count())) ? $count.' Day' : $count.' Day`s'; 
            ?>    
            <?php
            $variation = $this->statement->getBalance($this->statement->getEnd()->getDate())-$this->statement->getBalance($this->statement->getStart()->getDate());
            ?>
            <span style="color:<?php echo $variation<0 ? 'red' : 'green'; ?>;">
                &pound;<?php echo number_format($variation,2); ?>
            </span>
            
        </h5>
    </div>
    
    
    <div class="span8 pull-right">
                
        <div class="pagination pull-right"> 
            <ul>
                <?php foreach($this->months AS $month): ?>

                    <li 
                        class="<?php echo $this->today->format('Y-m')==$month->format('Y-m') ? 'active' : ($month->format('Y-m')=='2016-10' ? 'disabled' : ''); ?>" 
                        >
                        <a href="<?php echo $month->format('Y-m')=='2012-08' ? '#' : $this->url('statement', array('datestamp'=>$month->format('Y-m-d')));?>" >
                            <?php echo $month->format('M Y'); ?>
                        </a>
                    </li>
                <?php endforeach; ?>
                
            </ul>
        </div>
        
        
    </div>


    <div class="content span12">

        <table class="table table-striped table-hover table-bordered">
            <tr>
                <th>Date</th>
                <th>Transactions</th>
                <!--th><a href="<?php echo $this->url('dates', array('action'=>'add'));?>" class="btn btn-mini pull-right"><i class="icon-plus"></i></a></th-->
            </tr>
            <?php foreach ($this->statement as $date) : ?>
                <tr 
                    id="<?php echo $date->getDate()->format('mj'); ?>" 
                    class="<?php   

                    if ($date->getChecked()) { 
                        echo 'checked ';
                    }

                    $ymd_ = $date->getDate()->format('Ymd');
                    $dt_  = $date->getDate();            
		    
                    if ($this->today->format('Ymj')==$date->getDate()->format('Ymj')){
                        echo 'success '; 
                    } elseif ($this->statement->getBalance($dt_) < -2700){ 
                        echo 'error ';
        			} 
                    
                ?>"
                >
                <td>
                        <?php //echo $this->escapeHtml($date->getDate()); ?>                 
                        <p class="date"><?php echo $this->escapeHtml($date->getDate()->format('D jS \of M')); ?></p> 
                        <p class="<?php echo $this->statement->getBalance($date->getDate())<0 ? 'amt-negative' : 'amt' ?>">
                            &pound;<?php echo number_format($this->statement->getBalance($date->getDate()),2); ?>
                        </p>                         
                </td> 
                <td>
                        <!--div class="btn-group pull-right">  
                                <!--a href="<?php echo $this->url('transactions',array('action'=>'add', 'id' => $date->getId()));?>" class="btn btn-mini"><i class="icon-plus"></i-->                          
                                <!--a href="<?php echo $this->url('accounts',array('action'=>'delete', 'id' => $account->id));?>" class=""btn btn-mini"><i class="icon-trash"></i></a--> 
                                <!--a href="<?php echo $this->url('accounts',array('action'=>'activity', 'id' => $account->id));?>" class="btn btn-mini">
                                        <i class="icon-picture"></i>
                                </a>
                        </div-->                              
                        <?php if (intval($date->getTransactionTotal())!==0) : ?>
                            
                            <div class="pull-left">
                                <strong style="color:<?php echo $date->getTransactionTotal()<0 ? 'red' : 'green'; ?>;">
                                    &pound;<?php echo number_format($date->getTransactionTotal(),2); ?>            
                                </strong>  
                            </div>

                        <?php endif; ?>    

                        <div class="pull-right">

                            <?php if ($date->getChecked()) { ?>
                                <a href="<?php echo $this->url('transactions',array('action'=>'uncheck', 'id' => $date->getId()));?>" class="btn btn-mini">
                                    <i class="icon-wrench"></i> 
                                </a> 
                            <?php } else { ?>
                                <a href="<?php echo $this->url('transactions',array('action'=>'check', 'id' => $date->getId()));?>" class="btn btn-mini">
                                    <i class="icon-lock"></i> 
                                </a> 
                            <?php } ?>
                        </div>

                        <div class="clearfix"></div>

                        <?php if (intval($date->getTransactionTotal())!==0) echo "<hr />"; ?>


                        

                        <?php
                        
                        if (count($transactions = $date->getTransactions()) >0) {
                            foreach($transactions AS $transaction) : ?>

                                <div class="transactions-listing">
                                    <div class="btn-group pull-right">           
                                                                        
                                            <a href="<?php echo $this->url('transactions',array('action'=>'edit', 'id' => $transaction->id));?>" class="btn btn-mini">
                                                <i class="icon-pencil"></i>
                                            </a>
                                            <!--a href="<?php echo $this->url('transactions',array('action'=>'delete', 'id' => $transaction->id));?>" class="btn btn-mini">
                                                    <i class="icon-trash"></i>
                                            </a-->
                                            <a href="<?php echo $this->url('payments',array('action'=>'activity', 'id' => $transaction->payment->id));?>" class="btn btn-mini">
                                                <i class="icon-list"></i>
                                            </a>
                                    </div>  
                                                                 
                                    <p <?php echo $transaction->active ? "" : "class='muted'"; ?>>
                                            <span style="color:<?php echo $transaction->amount<0 && $transaction->active ? 'red' : ''; ?>;">&pound;<?php echo number_format($transaction->amount,2); ?></span>
                                            &nbsp;<?php echo $transaction->payment->description; ?>&nbsp;- <?php echo $transaction->payment->account->name; ?>&nbsp;
                                            <?php if ($transaction->comment!=='') : ?>
                                                <small><i><?php echo $transaction->comment; ?></i></small>
                                            <?php endif; ?>
                                    </p> 
                                </div>                        
                            <?php     
                            endforeach; 
                                 
                        } ?>
                        
                    </td>
                    <!--td>
                        <div class="btn-group pull-right">                            
                            <a href="<?php echo $this->url('dates',array('action'=>'edit', 'id' => $date->getId()));?>" class="btn"><i class="icon-pencil"></i></a>
                            <a href="<?php echo $this->url('dates',array('action'=>'delete', 'id' => $date->getId()));?>" class="btn"><i class="icon-trash"></i></a> 
                        </div>
                    </td-->
                </tr>
            <?php endforeach; ?>
        </table>
        
    </div>
    
    
</div>

<script type="text/javascript">
   
    $(function(){

        //$('html,body').animate({ scrollTop: $('#<?php echo $today->format('mj'); ?>').offset().top});
        $('html,body').animate({ scrollTop: $('#<?php echo $this->today->format('mj'); ?>').offset().top - 150});
    
    });
</script>
